#!/bin/sh

echo "=============================================================================================================="
echo "Checking commit name... ⏳"

INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^(feat|bug|ref):[[:space:]][A-Z]+[a-z[:space:]]+$"

if [[ ! $START_LINE =~ $PATTERN ]]; then
  echo "
  ⛔️
  There2 is something wrong with your commit message. \n
  Commit messages in this project must adhere to this contract: \n
  feat|bug|ref: Test commit message \n
  PS: First later after feat|bug|ref should be CAPITAL and with a space sign before
  ⛔️
  "
  exit 1
fi

echo "✅ Success! ✅"