version: '3'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - NODE_ENV=development
  #   environment:
  #     - SECRET_KEY=test
  #     - PORT=5000
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PASSWORD=waitr-password
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres:postgres
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo_data:/data/db